FROM golang:1.21-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o api-gateway ./cmd/main.go

FROM alpine:latest

WORKDIR /root/

COPY --from=builder /app/api-gateway .
COPY swagger.json .
COPY swagger-ui/ ./swagger-ui/

EXPOSE 8080

CMD ["./api-gateway"]
